# Generated by Django 4.0.5 on 2022-06-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_remove_neighbourhood_health_tell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_tell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
